### ISSUE TITLE
Project branding

### ISSUE THREAD

**Issue by vednoc** [userstyles-world/userstyles.world#1]
This project has been rewritten — we now have a proper server, database, etc. — the previous roadmap is no longer relevant.  The new roadmap can be accessed on GitHub's [Projects][1] page, which is a lot nicer than a simple checklist that we had.

Since this issue received many replies about design and branding, instead of closing it I've decided to rename it to "Project branding".

[1]: https://github.com/userstyles-world/userstyles.world/projects/1

**Comment by AbhayAysola** [comment]
Hi, I made a tiny logo. Tell me if I need to make any changes or if you're looking for something else.

![userstyles world](https://user-images.githubusercontent.com/67417765/94790345-c4493380-03f3-11eb-8de9-f544198eff29.png)

**Comment by AbhayAysola** [comment]
Hi @vednoc, it's a pleasure to help with this project. I think you're doing a great job. Are there any modifications I should make to mine or have you decided to use the one made by @RaitaroH? I'm also looking at the Hugo docs to see if I can be of any help with the actual development.

**Comment by vednoc** [comment]
I think a combination of your logo's background and Raitaro's 1st or 3rd icon would be the way to go. Maybe the background need to be darkened slightly. What do you think?

As for development, let me know how it goes. Hugo's documentation can be a bit overwhelming due to the amount of things you can do.

**Comment by AbhayAysola** [comment]
I agree with the darkening bit, it would suit the website better. The central icon is up to you.  This `{ S }` might also be good in the center. I just started the quickstart section in Hugo docs. I'll see how it goes.

**Comment by AbhayAysola** [comment]
![userstyles world 2-Darkened ](https://user-images.githubusercontent.com/67417765/94912696-a9df8a80-04c5-11eb-8dfa-de98ebabdee5.png)
This is the darkened version. @rRaitaroH could you send me the first and third icon in your logo so I can integrate it with mine?

**Comment by vednoc** [comment]
I think the first icon would look great! I don't know which one to pick, so I'll let you two decide. 😄

**Comment by AbhayAysola** [comment]
Sure.

**Comment by RaitaroH** [comment]
@AbhayAysola here is the goods:
[world_logo.tar.gz](https://github.com/vednoc/userstyles.world/files/5319904/world_logo.tar.gz)
For the ico:
`convert -background none icon.svg -define icon:auto-resize icon.ico`  is literally all that is needed and it works really nice

**Comment by AbhayAysola** [comment]
Thanks 👍

**Comment by AbhayAysola** [comment]
I'm using photoshop and I'm confused as to how I use the icons.... Any ideas?

**Comment by RaitaroH** [comment]
@AbhayAysola the icons are SVGs. They were made in Inkscape by [keeferrourke](https://github.com/keeferrourke/la-capitaine-icon-theme) and edited by me, also in Inkscape. You may open them in Adobe Illustrator I believe. If you need to I can export them in a png or something for you, any rez you want. BUT, you can just drag and drop an svg in GIMP and it will ask you what rez to import it in so I believe you only need to do the same in photoshop.

**Comment by AbhayAysola** [comment]
I'll try to use the icons, but just in case could you export the first one? The paintbrush one.

**Comment by AbhayAysola** [comment]
Never mind I figured it out 😄

**Comment by AbhayAysola** [comment]
![userstyles world](https://user-images.githubusercontent.com/67417765/94987785-a6f89e80-0586-11eb-8ce6-f4be925ba7f7.png)
If this is the final one, I can export as a png too.

**Comment by RaitaroH** [comment]
Up to @vednoc

**Comment by RaitaroH** [comment]
@AbhayAysola I looked at the logo in 32x32 but it won't work (same reason as my own scalable.svg won't work). I recommend using the symbolic.ico I provided.

**Comment by AbhayAysola** [comment]
I didn't understand what you meant by that. @RaitaroH

**Comment by RaitaroH** [comment]
Vednoc also wants a favicon, that is the little icon in your tab. That icon is very small, therefore detail will get lost. The .ico I provided takes in consideration how it looks at a very small size. I find that the globe should go, and we need to maximize the brush icon as much as possible in the available canvas area :)

**Comment by AbhayAysola** [comment]
![userstyles world](https://user-images.githubusercontent.com/67417765/94993064-f00f1980-05ab-11eb-927b-3c4ef9531737.png)
Would this be better?

**Comment by AbhayAysola** [comment]
![userstyles world](https://user-images.githubusercontent.com/67417765/94993109-4419fe00-05ac-11eb-9ebe-2c9fcfce9f8f.png)
Sorry, wrong one.

**Comment by RaitaroH** [comment]
Yes, that is better. It can work as a favicon now.

**Comment by AbhayAysola** [comment]
Should I export as SVG as well?

**Comment by RaitaroH** [comment]
Yes. If you can if .ico sure, or I can do it from the svg.

**Comment by AbhayAysola** [comment]
Ok, SVG isn't supported in the comments upload, so should I mail it?

**Comment by RaitaroH** [comment]
Zip it and drop it here

**Comment by AbhayAysola** [comment]
[userstyles.world.zip](https://github.com/vednoc/userstyles.world/files/5321779/userstyles.world.zip)
I zipped the svg along with the png :)

**Comment by RaitaroH** [comment]
[userstyles.world.zip](https://github.com/vednoc/userstyles.world/files/5321785/userstyles.world.zip)
Here is also the favicon.ico file. @vednoc check em out.

**Comment by vednoc** [comment]
Looks awesome, thanks! I'll run a few tests to see if something needs to be tweaked further. 😄

**Comment by amanharwara** [comment]
I think a name change might be warranted because "UserStyles.world" is a bit lengthy and generic. This is just my opinion of course, but I think it's something you should consider.

**Comment by amanharwara** [comment]
Also, I had some time, so I came up with this design:

![userstylesworld](https://user-images.githubusercontent.com/8348101/98919074-513cdd80-24c6-11eb-8b55-70dacd9f628f.png)

If you like it, let me know and I'll create the designs for the other pages.

**Comment by AbhayAysola** [comment]
Wow! That looks nice. The logo I made looks amateurish now 😅. I might have to redo it sometime. Cool design though.

**Comment by vednoc** [comment]
> I think a name change might be warranted because "UserStyles.world" is a bit lengthy and generic.

Maybe! I'm not opposed to the idea. After all, I'd love this project to be "for the community, by the community".

> If you like it, let me know and I'll create the designs for the other pages.

It looks pretty good! My exploration from yesterday went into a similar direction. Here's a screenshot:

![Screen Shot 2020-11-11 at 12 11 49](https://user-images.githubusercontent.com/18245694/98939783-3f6d3180-24ea-11eb-9550-7543ddddb602.png)

**Comment by amanharwara** [comment]
That looks very good! I went for a center-aligned hero section as well, but it felt a little off to me so I left-aligned it and used the logo to fill the right side a bit.

**Comment by vednoc** [comment]
I'll try it out with the logo. It has the potential to look great. ⭐

**Comment by vednoc** [comment]
I've updated my [initial comment][1] with new information.

[1]: https://github.com/userstyles-world/userstyles.world/issues/1#issue-684950831
