### ISSUE TITLE
Mirrior update Fail for some userstyles...

### ISSUE THREAD

**Issue by decembre** [userstyles-world/userstyles.world#101]
I think i understand how to do for mirror update, i read your help about it, but...

By example this was updated on Userstles.org and USO (v.9to v.10):
<a href="https://userstyles.world/style/67/flickr-widescreen-viewer-flickriver-v-9">Flickr WideScreen (Viewer) - FlickRiver</a>

But it is not updated to USw.

Seems there is the same problem with an other by example:
<a href="https://userstyles.world/style/28/userstyles-greasy-fork-enhancer-dark-grey-v-202">Userstyles / Greasy Fork Enhancer Dark-Grey v.202</a>
For this one, i make the update by hand.
Now, for the next update on userstyles.org, it can be updated?
Or i broke something ?

I notice a BBcode problem  (<code>`</code>) around its description imported:
Maybe that's break the update ?
Normaly it should be fixed, as you said here:
<a href="https://github.com/userstyles-world/userstyles.world/issues/32">The Description Section don't keep the original text formatting (but that's good in the Notes section):    That's a bug. I'll fix it for the next release.</a>

Other things:
When i wanted try something to have this auto update, i try to add in the form:
"Mirror source code URL
If your style was imported, this takes priority over original URL."
the url of UserCSS from USO (the same i used for the import):
https://raw.githubusercontent.com/33kk/uso-archive/flomaster/data/usercss/126659.user.css

Not the solution, no update of the userstyle.

But when i wanted remove my change, it is not possible.
I see it always in the userstyle info page and its edit page.

I tested the same thing with:
<a href="https://userstyles.world/style/28/userstyles-greasy-fork-enhancer-dark-grey-v-202">Userstyles / Greasy Fork Enhancer Dark-Grey v.202</a>

**Comment by vednoc** [comment]
I believe this is due to USo-archive's mirroring of userstyles, [which is set to every 12 hours][1]. The versions that I'm seeing are the same ones you can see in USo-archive; if they weren't mirrored from USo, then the issue happens over there. We still check for updates on every 30 minutes, which I'll increase to every 60 minutes or more in v2.0 of USw. 

To summarize, it all depends on the timing of you pushing your changes to USo and USo-archive mirroring them.

> I notice a BBcode problem (`) around its description imported [...] Maybe that's break the update ?

Nope, that's doesn't matter. As for rendering metadata mirrored from USo-archive, I have a way to decouple it from being processed by our Markdown engine, but it's a hack-y solution that requires some safe-guarding. 

>  But when i wanted remove my change, it is not possible.

Oh, right, this is something I forgot to implement. It's because empty fields are skipped if we don't use a specific way to tell what should be updated in the database.

[1]: https://github.com/33kk/uso-archive/commit/e6b49114de94e6193ec7fc14f50b760a17fb6eb1

**Comment by decembre** [comment]
Thanks!
I remember of this timing thing.

The update seems working for all (a part the BBcode problem), as i can see...all, but not the screenshot.
By example for:
<a href="https://userstyles.world/style/67/flickr-widescreen-viewer-flickriver-v-13">Flickr WideScreen (Viewer) - FlickRiver</a>

**Comment by vednoc** [comment]
Yep, we don't have the logic to handle mirroring screenshots. Not sure if we want it to be another option, or if we should include it in the "mirror metadata" option. I suppose the former makes more sense.

**Comment by decembre** [comment]
So, for now we need to update the screenshot our self?

I don't remember well, but it seems that for other userstyles, the auto update take care to the screenshot too...
I am not certain.

**Comment by vednoc** [comment]
Yes, for now. We only have logic to handle screenshots when creating/importing userstyles. There's nothing in the [updater module][1] that checks whether the screenshots are the same or not.

[1]: https://github.com/userstyles-world/userstyles.world/blob/v1.7.0/modules/update/archive.go

**Comment by decembre** [comment]
Ok!
;-)

**Comment by decembre** [comment]
Seems have a problem too for this one (it stay at v.27)
<a href="https://userstyles.world/style/27/youtube-widescreen-new-design-polymer-v-27">[Youtube WideScreen (New Design Polymer) v.27](https://userstyles.world/style/27/youtube-widescreen-new-design-polymer-v-27)</a>

Mirror uso-archive.surge.sh (v.28), Updated at: 09/10/2022 à 15:29:40:
<a href="https://uso-archive.surge.sh/?sort=updated&amp;author=decembre&amp;style=188453">[Youtube WideScreen (New Design Polymer) v.28](https://uso-archive.surge.sh/?sort=updated&author=decembre&style=188453)</a>

**Comment by vednoc** [comment]
Looks like it's still cached on the [CDN](https://cdn.jsdelivr.net/gh/33kk/uso-archive@flomaster/data/usercss/188453.user.css):

![image](https://user-images.githubusercontent.com/18245694/194941947-8ac8d0ba-f918-4367-b629-be5ffe199c53.png)

**Comment by decembre** [comment]
I don't understand:
my last version is v.28

**Comment by vednoc** [comment]
Yes, but it hasn't updated on `cdn.jsdelivr.net`, which is from where your userstyle is mirrored. USo-archive uses GitHub's own [CDN](https://raw.githubusercontent.com/33kk/uso-archive/flomaster/data/usercss/188453.user.css), which does have the latest version of your userstyle. Try setting "Mirror source code URL" to use GitHub's link. That should work.

**Comment by decembre** [comment]
From uso.kkx.one (work for me now, before it don't with Waterfox classic..):
<a href="https://uso.kkx.one/style/188453">[Youtube WideScreen (New Design Polymer) v.28](https://uso.kkx.one/style/188453)</a>
I need to copy this link (from the "View JSON" button):
https://cdn.jsdelivr.net/gh/33kk/uso-archive@flomaster/data/styles/188453.json

In the field of:
"Mirror source code URL - If your style was imported, this takes priority over original URL."
That's right?

Sorry, the "If your style was imported, this takes priority over original URL" don't be very clear for me...
:-)

**Comment by vednoc** [comment]
Nope. On old USo-archive version, you can either copy the "UserCSS" link or the link on "Install" button. They're the same. It's this link that you need to put in that field:

- https://raw.githubusercontent.com/33kk/uso-archive/flomaster/data/usercss/188453.user.css

On new USo-archive version, you can copy the "Install with Stylus" link, but it might have cache issues. You get this:

- https://cdn.jsdelivr.net/gh/33kk/uso-archive@flomaster/data/usercss/188453.user.css

I suppose we might want to overwrite that with a link to GitHub. Any thoughts, @Gusted? Additionally, we should make its description more clear.

**Comment by decembre** [comment]
Ok i put the first link and wait and see....
This way don't change nothing for the stats ?

Note around:
I suggested some time ago a "Stats keeper " function (by example, show the number of installs since the last refresh by example):
seems accepted, but....

**Comment by vednoc** [comment]
It should mirror in 10 minutes. If it doesn't, I'll have another look tomorrow.

As for stats, there's a rewrite coming up that will redo everything. Once those changes are in, we should able to show you stats since you were last logged in or something along those lines.

**Comment by decembre** [comment]
Fine, as usual!

**Comment by decembre** [comment]
Yes!
Big thanks man!
But before it was updated normally... strange, no ?

**Comment by vednoc** [comment]
You're welcome! It would've updated at some point, but not sure when. Perhaps we could change mirroring from every 30 minutes to every few hours, because we could be preventing their cache refresh/invalidation.

**Comment by decembre** [comment]
I let you put your hands in the machine with pleasure!

**Comment by decembre** [comment]
Seems the return of the same problem  for this userstyle....

I test the other link you give to me:
https://cdn.jsdelivr.net/gh/33kk/uso-archive@flomaster/data/usercss/188453.user.css

**Comment by vednoc** [comment]
I find it fascinating that there's a log message how it was mirrored, yet the versions don't match. Could you put `https://raw.githubusercontent.com/33kk/uso-archive/flomaster/data/usercss/188453.user.css` as the mirror URL? I might go ahead and rewrite all jsdelivr URLs. P.S. We did change mirroring from 30 minutes to every 4 hours and that might've had some effect, though it's impossible to tell.

**Comment by decembre** [comment]
The problem around  BBcode problem (`) seems always present too...
That's why i update only the code.

I do your suggestion when in do my next release (YouTube change perpetually...)

**Comment by vednoc** [comment]
I can see that there's a difference in what you get when importing from jsdelivr and githubusercontent links. That's the reason why it would be good to rewrite these links instead of treating them differently. IIRC we used to this better before USo-archive switched to jsdelivr.

**Comment by decembre** [comment]
> hat's the reason why it would be good to rewrite these links instead of treating them differently.

On your side or mine ?

**Comment by decembre** [comment]
New version published:
 v.32

Change for update link done to (but that was the same that previously i used):
https://raw.githubusercontent.com/33kk/uso-archive/flomaster/data/usercss/188453.user.css

wait and see...

**Comment by vednoc** [comment]
On our side. I got a part of the metadata when using githubusercontent link and the entire metadata when using the jsdelivr link. That's because we treat the latter [as a special link](https://github.com/userstyles-world/userstyles.world/blob/9a4695ce07027291e8af761a79e9f5a829c4c34b/utils/archive.go). Maybe it's time to promote this file to a module and handle things properly.

**Comment by decembre** [comment]
What a work for you!

I need to revert to ?:
https://cdn.jsdelivr.net/gh/33kk/uso-archive@flomaster/data/usercss/188453.user.css

**Comment by vednoc** [comment]
Nope. Keep it as is.

**Comment by decembre** [comment]
Ok...

**Comment by vednoc** [comment]
In retrospect, I should've rewritten the URL in this commit: https://github.com/userstyles-world/userstyles.world/commit/14271785aefa77a456a14bc7eb011050962b40c1 Oh well, more technical debt for me to deal with. (=

**Comment by vednoc** [comment]
This issue should be resolved. @decembre, you can now also use links to pages on either new or old USo-archive to import userstyles instead of their install URLs. That is, the following URLs are all exactly the same:

- https://uso.kkx.one/style/188453
- https://uso-archive.surge.sh/?style=188453
- https://cdn.jsdelivr.net/gh/33kk/uso-archive@flomaster/data/usercss/188453.user.css
- https://raw.githubusercontent.com/uso-archive/data/flomaster/data/usercss/188453.user.css

As such, they will all be rewritten to use the very last URL—the origin—and all caching issues from jsdelivr should be gone.
