### ISSUE TITLE
Move Link New Style when uploading from Stylus to the beginning of the list

### ISSUE THREAD

**Issue by Freeplayg** [userstyles-world/userstyles.world#102]
This thing, in case you have a lot of styles.
![2022-01-10_12-03](https://user-images.githubusercontent.com/40742947/148809043-a4dc8406-c7ec-461d-a8c2-60b9f6de090c.png)

**Comment by Gusted** [comment]
https://github.com/userstyles-world/userstyles.world/commit/b70d545a1cbb5c92ca20f442f59de5d955600408
