### ISSUE TITLE
Stolen Style, Asking For Takedown (Again)

### ISSUE THREAD

**Issue by Ticpo-01** [userstyles-world/userstyles.world#104]
### I would like to be able do the following: Asking for takedown of stolen style (again)

1. I had reported this user last time and they have again uploaded another one of my styles
2. Asking again if the style can be taken down
3. Link of stolen style: https://userstyles.world/style/2767/minecraft-style-for-jdn-2-0 (They once again left my name in the @author section of the code)
4. Original link of style: https://greasyfork.org/en/scripts/424267-minecraft-style-for-jdn

### Additional context

Also created an account and am working on porting my styles over to (hopefully) prevent this from happening again

**Comment by vednoc** [comment]
Removed it. Let's hope the user in question doesn't do it again.
