### ISSUE TITLE
Unicode caracters wrong formated when i test  install without Stylus

### ISSUE THREAD

**Issue by decembre** [userstyles-world/userstyles.world#107]
I tested on a new profile of Waterfox Classic, the install without Stylus addon instaled.
by example for this userstyle:
<a href="https://userstyles.world/style/248/flickr-widescreen-bigone-v-187">Flickr WideScreen - BigONE</a>

When i  click on install button, it open a page:
https://userstyles.world/api/style/248.user.css

I copy paste in my Old Stylish editor, cut the to header:
/* ==UserStyle==
... / ...
==/UserStyle== */

The userstyles work, but strangely, it convert some Unicode, like that:

From:
.context-slider-scrappy-view .context-slider > .nav-l span:before {
    content: " ◄" ;
}
.context-slider-scrappy-view .context-slider > .nav-r span:before {
    content: "►" ;
}

To this:

.context-slider-scrappy-view .context-slider > .nav-l span:before {
    content: " â—„" ;
}
.context-slider-scrappy-view .context-slider > .nav-r span:before {
    content: "â–º" ;
}

Note:
If i copy paste from the Stylus install page:
moz-extension://7e918a81-c4ab-41a3-907f-0fa911dc1813/install-usercss.html?updateUrl=https%3A//userstyles.world/api/style/248.user.css
that's ok...

**Comment by Gusted** [comment]
This is a bug with waterfox classic, they aren't using UTF-8 encoding on raw files(even when specified that they should do that). Not much we can do here actually.

**Comment by decembre** [comment]
Thanks

**Comment by decembre** [comment]
So, after the request to Waterfox, i return to you:
<a href="https://github.com/WaterfoxCo/Waterfox-Classic/issues/63">[It's possible to serve it with UTF-8 encoding header but that should be done by whoever owns userstyles.world](https://github.com/WaterfoxCo/Waterfox-Classic/issues/63) [Waterfox-Classi GitHub]</a>

**Comment by Gusted** [comment]
> So, after the request to Waterfox, i return to you:
> [It's possible to serve it with UTF-8 encoding header but that should be done by whoever owns userstyles.world](https://github.com/WaterfoxCo/Waterfox-Classic/issues/63) [Waterfox-Classi GitHub]

That's pretty funny, because 

> (even when specified that they should do that).

when I tried this issue out, I added the suggested content-encoding as a header(as we don't want nor really can safely modify .user.css to add `@charset`). But water-fox safely ignored it. I can still add the patch to add this behavior and try it for yourself.

**Comment by Gusted** [comment]
@vednoc Would you be so kind to update the production server? to includes 1246e3619a4a647dd864c45eb23aad8c5aed3db1

**Comment by vednoc** [comment]
> @vednoc Would you be so kind to update the production server? to includes [0b29e86](https://github.com/userstyles-world/userstyles.world/commit/0b29e865268b7c8568d48b861407cd3d3bebeb2a)

I was running an experiment to see how long USw would run with previous optimizations, but I suppose ~131 hours is a decent stopping point. The server has been updated.

**Comment by decembre** [comment]
I re test your change.
Yes now no error  UTF-8 encoding in the user.css.

- Stylus disable:
Now it propose to save it or open with XX
Not directly open in a tab.
- Stylus enable:
Work as expected (open the Stylus user.css install.

Thanks folks!

**Comment by reallyuniquename** [comment]
@Gusted 
>when I tried this issue out, I added the suggested content-encoding as a header(as we don't want nor really can safely modify .user.css to add @charset). But water-fox safely ignored it

Sending `Content-Type: text/css; charset=utf-8` fixes it for me on Waterfox Classic.

https://github.com/userstyles-world/userstyles.world/commit/0b29e865268b7c8568d48b861407cd3d3bebeb2a#diff-662de3ce5aab8c07a72e779bb1ffa953b554d933e4b478d92e6afc8bc515424bR52

The actual header being sent is `content-type: application/octet-stream; charset=utf-8` so it just shows "Save file as" dialog now, i.e. charset doesn't really matter.

**Comment by Gusted** [comment]
f6cbe8721238b6f0b79b0ab4a4615e1ac4503da2

**Comment by vednoc** [comment]
The server has been updated once again. Please give me a confirmation that it works properly this time around.

**Comment by reallyuniquename** [comment]
All good, the server sends correct headers as per W3C standards so all browsers should handle it correctly now.
