### ISSUE TITLE
Explore filter by XX: none accurate ?

### ISSUE THREAD

**Issue by decembre** [userstyles-world/userstyles.world#109]
If you go to:
<a href="https://userstyles.world/explore?page=1&amp;sort=mostviews">[Explore- mostviews](https://userstyles.world/explore?page=1&sort=mostviews)</a>
you can notice than the most viewed score drop quickly on the first page:
begin to 3.3k views to finish at 53 views.
And they are a few in the 3k to 1k range:
If i see one of my userstyle with 1.1k view, it is strange to not see it in this explore first page.

That's seems the same thing with the "Most installs" filter.

**Comment by Gusted** [comment]
The pagination is incorrect here. CC @vednoc
