### ISSUE TITLE
Account Socials doesn't allow proper Gitlab usernames

### ISSUE THREAD

**Issue by miguelfradinho** [userstyles-world/userstyles.world#110]
When editing user profile to add Gitlab under "Social", I'm unable to enter my username because it has the dot in it (thus 404'ing the link when viewing my profile).

- **Additional context**:
From checking the source code, it seems the issue relies on the pattern being used to match, which might have just been because of reusing Github's username pattern? Gitlab differs slightly as it accepts usernames with separated by some punctuation characters.

Current input element under https://userstyles.world/account 
```html
<input pattern="^[a-zA-Z0-9_-]*$" type="text" 
name="gitlab" placeholder="Your username" value="potato.man">
```
![imagem](https://user-images.githubusercontent.com/24386108/154848682-40681075-7114-412f-86d1-61674ad8e86a.png)

Whereas Gitlab uses a more elaborated pattern (truncated classes and data-selectors for relevance) in their sign-up form https://gitlab.com/users/sign_up

```html
<input pattern="[a-zA-Z0-9_\.][a-zA-Z0-9_\-\.]*[a-zA-Z0-9_\-]|[a-zA-Z0-9_]" 
required="required"
title="Please create a username with only alphanumeric characters." 
type="text" name="new_user[username]" id="new_user_username">
```
![imagem](https://user-images.githubusercontent.com/24386108/154848792-f5654db0-6ee8-41a7-a0ca-c5a32038ddc8.png)

- **Browser**: Not relevant as the issue is due to the pattern , reproducible on both Chromium-based Edge (98.0.1108.56) and Firefox (97.0.1)

**Comment by vednoc** [comment]
I deployed the fix and everything works now. I also managed to include the dot in GitHub's regex, but it shouldn't matter and it will be removed later. 😅 

Thank you for reporting this issue!
