### ISSUE TITLE
Thumbnails take ages to update on current device.

### ISSUE THREAD

**Issue by blyad2137** [userstyles-world/userstyles.world#113]
- **Browser**: Doesn't Matter (Opera GX, Firefox, Chrome if must)
- **Screenshot**: <img src="https://i.imgur.com/5lptFaX.png"></img> My PC vs my phone
- **Additional context**: After updating thumbnail it takes ages to see the effects on device it was send from.
Changes take immediate effect on other devices tho.

**Comment by Gusted** [comment]
IIRC @vednoc was working on making caching invalidation work via hashes of the image.

**Comment by vednoc** [comment]
I'll try to finalize my exploration/prototype and deploy it tonight. It should also include thumbnails (#77).
