### ISSUE TITLE
How to report an unauthorized upload of one of my styles?

### ISSUE THREAD

**Issue by FSA1** [userstyles-world/userstyles.world#114]
I would like to report an unauthorized upload of one of my styles but don't no how. I don't find any channel in the site.

This is the link to the unauthorized upload: https://userstyles.world/style/2955/chess-com-chess-set-furia-pack
here is my blog on chess.com where I post my styles: https://www.chess.com/pt-BR/blog/Agiota_do_Artenio/pantera-da-furia-no-lugar-do-cavalo-sim-tabuleiro-e-pecas-da-furia
ChessSkins or agiota_do_artenio are both my nicks.

* I speak Portuguese, sorry if my English is not good.

**Comment by vednoc** [comment]
Your English is pretty good. In the future we'll have an internal report system (#73), but for the time being it's best to request it via mail, Discord, or Matrix, so that our issue tracker is free of off-topic requests. With that said, I removed the userstyle. You can see it in our [modlog](https://userstyles.world/modlog#id-58).

**Comment by FSA1** [comment]
Hello vednoc, I will post more styles soon. I just want to have control over my work to keep it up to date and well organized. Thanks for the quick reply, keep up the good work!Enviado do Email para Windows De: vednocEnviado:quinta-feira, 26 de maio de 2022 10:32Para: userstyles-world/userstyles.worldCc:FSA; AuthorAssunto: Re: [userstyles-world/userstyles.world] How to report an unauthorized upload of one of my styles? (Issue #114) Your English is pretty good. In the future we'll have an internal report system (#73), but for the time being it's best to request it via mail, Discord, or Matrix, so that our issue tracker is free of off-topic requests. With that said, I removed the userstyle. You can see it in our modlog.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
