### ISSUE TITLE
link edit mode

### ISSUE THREAD

**Issue by jorjik** [userstyles-world/userstyles.world#119]
- **Browser**: Yandex-Browser
- **Screenshot**: https://i.imgur.com/vrqbTyh.png

**Comment by Gusted** [comment]
What's the issue?

**Comment by jorjik** [comment]
https://i.imgur.com/MtzaZQd.gif

**Comment by Gusted** [comment]
I'm sorry, but sending a GIF isn't enough to say what the issue here is. That wasn't recorded on userstyles.world, so there's no clear indication what the bug is about.

**Comment by vednoc** [comment]
It looks like an issue some userstyle. @jorjik, is that correct?

**Comment by jorjik** [comment]
Yes, in the 3rd field the text and the background merge into one

**Comment by vednoc** [comment]
Please try reaching out to userstyle author(s) when you have issues with their userstyles. The issues here aren't meant to be used for reporting bugs with userstyles. With that said, the author of this userstyle is in our Discord server, so I'll let him know.
