### ISSUE TITLE
Sort our usertyles by date / name / most /install / daily install etc...

### ISSUE THREAD

**Issue by decembre** [userstyles-world/userstyles.world#120]
It should be great if yo add these functions.
The default sort seems the most install in first, but it's not sufficient for me :-)

It's arelated to:
<a href="https://github.com/userstyles-world/userstyles.world/issues/46">[Add style statistics #46](https://github.com/userstyles-world/userstyles.world/issues/46)</a>

**Comment by vednoc** [comment]
The default sorting method is from oldest to newest based on the time it was created.

**Comment by decembre** [comment]
Yes....
:-)
