### ISSUE TITLE
Can't switch to login with email/password from OAuth provider

### ISSUE THREAD

**Issue by Black-Platypus** [userstyles-world/userstyles.world#122]
After registering with GitHub, I'd like to switch to an independent login using email and password.
This is offered by the login form.
However, upon setting a password using the "forgot my password" procedure, I still can't log in independently, the site just tells me to use "Login via OAuth provider"
At least I think that that's what it wants to tell me by just saying "Login via OAuth provider".
_(As far as I'm concerned, "login" is a noun; the verb should be "log in", so if the above interpretation is correct, maybe change the message?)_

As the site both

- Offers login via email + PW
- Has my email and PW:

    ![image](https://user-images.githubusercontent.com/13470026/183509354-8307306b-5fbc-4c15-8602-373bc9479185.png)

It should enable logging in this way.

- **Browser**: Current-ish Chrome
- **Screenshot**: 
![image](https://user-images.githubusercontent.com/13470026/183508670-80e9c035-14e2-4c2a-9a18-35e2faeca101.png)

**Comment by vednoc** [comment]
@Gusted I wonder, is there any particular reason for this check?

https://github.com/userstyles-world/userstyles.world/blob/f5b5ee800f777ca44dcb773a4351f0a3ff59e978/handlers/user/login.go#L66-L72

As for suggesting to change the message, thank you for pointing that out. English isn't my first language and I still have a lot to learn. 😄

**Comment by svArtist** [comment]
> English isn't my first language and I still have a lot to learn. 😄

Oh 😊 
Mine either, but I think something like "Please log in via OAuth provider" would be a bit clearer

**Comment by vednoc** [comment]
Sounds good to me. Ideally, we wouldn't need to have this warning. I don't know why it's there, but I do know we need to rethink how we deal with OAuth.

**Comment by vednoc** [comment]
Hey @svArtist, I've just deployed a new update and it would be awesome if you could confirm whether the issue has been resolved. If it is, I'll close it by merging the commits into main branch.

**Comment by svArtist** [comment]
Yes! Neat-o!
Thank you, I could use the new login directly, didn't even have to set a password again 😊 👍

**Comment by vednoc** [comment]
For posterity, I've allowed leaving the "current password" empty for those that signed up via OAuth, so that new passwords can be set without using the "forgot my password" hack. 😄
