### ISSUE TITLE
style page display error

### ISSUE THREAD

**Issue by XiaoPanPanKevinPan** [userstyles-world/userstyles.world#124]
- **Browser**: Firefox v103.0.2 (64bit, Debian)
- **Screenshot**: 
  - below is a screenshot of [my user profile]( https://userstyles.world/user/xiaopanpankevinpan )
    ![image](https://user-images.githubusercontent.com/44266832/186692678-07399fee-8908-49d3-9e17-c2ba62ffc575.png) 
  - below is a screenshot of [my style, _Discord Minimize Sidebars_]( https://userstyles.world/style/4877/discord-minimize-sidebars )
    ![image](https://user-images.githubusercontent.com/44266832/186694886-d75d610f-78bd-4432-a8c6-b89fcb9b648b.png)

- **Additional context**: 
  - The pages of specific styles display this error: `template: partials/head:24:55: executing "partials/head" at <fullImage>: error calling fullImage: runtime error: slice bounds out of range [:-6]`. 
  - It is worth noticing that in a user's profile, the "search" page, or the "explore" page, those styles which are most likely to meet this problem are usually unable to display their thumbnails.

**Comment by vednoc** [comment]
A small oversight on my part while refactoring SEO code that broke rendering of all styles without preview images. 😅 Thank you for reporting the issue!
