### ISSUE TITLE
Error while attempting to log in to userstyles.world for first time using GitHub account

### ISSUE THREAD

**Issue by jlukosky** [userstyles-world/userstyles.world#132]
- **Browser**: Edge
- **Screenshot**: 
![image](https://user-images.githubusercontent.com/6210178/200067051-dcc19a29-db45-4f91-b55e-133bc94eeb26.png)
- **Additional context**: Trying to log in to userstyles.world with my GitHub account but with no luck.  Error returned: `{"error":"bad endpoint"}`. I'm anxious to contribute.

**Comment by vednoc** [comment]
@Gusted I can see that logs point to this line: https://github.com/userstyles-world/userstyles.world/blob/9a4695ce07027291e8af761a79e9f5a829c4c34b/handlers/api/callback.go#L103

In the database, the OAuth provider is set to "none". Does it mean when someone registers manually then tries to log in via OAuth we never updated it? This is confusing.

@jlukosky I'd like to know if you can log in with your credentials.

**Comment by jlukosky** [comment]
1. Tried logging in with GitHub again and same thing is happening.
2. I tried to create an account with email/password but that didn't work. After verifying my email I get an error that says "failed". 

Sooo, I can't log in either way.

**Comment by vednoc** [comment]
Our OAuth is kinda due for a rewrite. To make things simple, I'll do a (soft) delete of your account and you should be able to create a new one using OAuth.

**Comment by vednoc** [comment]
You may need to first revoke the access from this page: https://github.com/settings/applications

**Comment by jlukosky** [comment]
I tried again and let GitHub authorize userstyles.world. When I get to userstyles.world I don't see anything that would lead me to believe I'm logged in. There's still a sign in for example. If I click it I get the bad endpoint error. 

Am I logged in and just don't know it?

**Comment by vednoc** [comment]
Nope, I don't think so. I've just changed this field in the database, so you might be able to log in using OAuth now. It's pretty strange as we didn't have any issues like this before, so it might be something else at play. Gusted implemented this and they probably have a better idea of what's going on.

**Comment by Gusted** [comment]
> In the database, the OAuth provider is set to "none". Does it mean when someone registers manually then tries to log in via OAuth we never update it? This is confusing.

Well this means, someone registered on USw with the name "HelloWorld" and then tries to login via Github which also has the name of "HelloWorld", but on USw it was never set that Github's name is "HelloWorld".

**Comment by jlukosky** [comment]
Okay, I've registered using a different email address, so I'm unblocked. Sorry for mucking it up for you and thanks for you quick assistance!
