### ISSUE TITLE
Changing GitHub username creates a new user in Userstyles.World

### ISSUE THREAD

**Issue by NECO-des** [userstyles-world/userstyles.world#134]
After changing your GitHub username and trying to log in into your Userstyle account, it creates a new user with your new GitHub username.

The real issue is: when someone creates a GitHub account with my old username, they can access to my old Userstayle account and its styles with OAuth sign in.

Old account (which is now accessed with a fake GitLab account using my old username, it was originally created with a GitHub OAuth login): 
- https://userstyles.world/user/nabqz

The new account which was automatically created when I tried to log in: 
- https://userstyles.world/user/neco-des

**Comment by vednoc** [comment]
I've been waiting for @Gusted to rewrite OAuth since I don't fully understand how it works. Until that happens, I'll release a patch that disables OAuth altogether. As for your accounts, I'll let you know once I resolve the issue manually.

**Comment by NECO-des** [comment]
Thanks. 
For these two accounts, I'll probably want to delete them, but currently there's no "delete account" option, so my accounts are not that important for me, for now.

**Comment by vednoc** [comment]
OAuth has been blocking account-based functionality for a while now. Considering that I have a rudimentary idea of how it works, I'm not entirely sure how to move forward without breaking things in unexpected ways.

**Comment by vednoc** [comment]
This issue should be fixed now. There's still no way for you to delete your account(s), but we'll implement that pretty soon.
