### ISSUE TITLE
OAuth - Estimate for being re-enabled?

### ISSUE THREAD

**Issue by TheEmeraldKytten** [userstyles-world/userstyles.world#136]
On userstyles.world, OAuth login is disabled. 
Y'all explained why and I understand, no need to repeat yourself.  (For those wondering, here: "I've been waiting for Gusted to rewrite OAuth since I don't fully understand how it works. Until that happens, I'll release a patch that disables OAuth altogether." in issue #134)
However, I am wondering if you have any kind of estimate as to how long until OAuth gets re-enabled? I currently can't log into my UserStyles because I logged in with GitHub,

Thanks in advance!

**Comment by vednoc** [comment]
I apologize for the long delay. The ETA is waiting for code review on #137. The fix will be live when this issue is closed.

**Comment by TheEmeraldKytten** [comment]
Alright, thank you! Best of luck to you and the rest of the developers!

**Comment by wfurphy** [comment]
I'm also unable to login to my account! Any ETA yet?

**Comment by vednoc** [comment]
Once more, I apologize for the even longer delay. The PR is ready to be merged, unless there's something I overlooked while rewriting the code. Gusted seems to be busy, so it might take a bit more time until it's ready.

**Comment by Gusted** [comment]
OAuth has been re-enabled.
