### ISSUE TITLE
My stylus crashed. I am unable to open it  and it disappear from the toolbar.

### ISSUE THREAD

**Issue by sapondanaisriwan** [userstyles-world/userstyles.world#140]
- **Browser**: Microsoft Edge Version 108.0.1462.54 (Official build) (64-bit)
- **Screenshot**:  
![image](https://user-images.githubusercontent.com/64634605/211014086-e87a5723-050c-4622-9210-6e2cb64feb59.png)

![image](https://user-images.githubusercontent.com/64634605/211014114-c88605e0-83bb-487d-aaab-431a75422a46.png)

**Comment by vednoc** [comment]
Wrong project. Report it here: https://github.com/openstyles/stylus
