### ISSUE TITLE
Allow users to delete their styles

### ISSUE THREAD

**Issue by sapondanaisriwan** [userstyles-world/userstyles.world#142]
**Describe the change you'd like**:
 I think it would be useful to add an option to delete the style(I have create too many styles so I want to delete some of them)

**Additional context**:

**Comment by vednoc** [comment]
Did you miss the delete button?

![image](https://user-images.githubusercontent.com/18245694/216769285-36ac620c-babb-437e-b98c-1a162416f1a9.png)

**Comment by sapondanaisriwan** [comment]
Oh sorry. I didn't notice it. lol 🤣
