### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by stashymane** [userstyles-world/userstyles.world#143]
After clicking on the email verificaftion link, I get the following page:
![image](https://user-images.githubusercontent.com/4071883/217859254-9781a480-6e06-40af-9711-05074de795e8.png)

No explanation or error message, just failed to register.

- **Browser**: Firefox
- **Additional context**: Disabling tracking protection changes nothing.

**Comment by vednoc** [comment]
There's already an account with your email address that signed up via OAuth. Since OAuth accounts have no passwords, go to https://userstyles.world/recover, use that email address, and you should be able to access your account once again.

**Comment by stashymane** [comment]
Would be nice to have an error message to tell me that, but your instructions worked, thanks :)
