### ISSUE TITLE
can't register

### ISSUE THREAD

**Issue by placeboyue** [userstyles-world/userstyles.world#148]
after clicking on the confirmation link on my email it says REGISTRATION FAILED.
Please fix this, i have a bunch of dark mode themes that i'd like to share so i can use them on other computers easily. And maybe others will also appreciate

- **Browser**:
- **Screenshot**:
- **Additional context**:

**Comment by vednoc** [comment]
Go to https://userstyles.world/recover and follow the steps. Your email address is the same one you use for GitHub, unless you changed it after signing up for USw.

**Comment by vednoc** [comment]
Looks like this is fixed now. @placeboyue, I'd also like to let you know that OAuth has been re-enabled, so you can use GitHub to sign in along with signing in using your email and password.
