### ISSUE TITLE
I would like to sign in....

### ISSUE THREAD

**Issue by daslastic** [userstyles-world/userstyles.world#149]
- **Browser**:
- Google Chrome, MacOS
- **Screenshot**:
<img width="1798" alt="image" src="https://user-images.githubusercontent.com/44515019/224843649-3468c446-78f1-4da0-89ea-3dcec43bf4b3.png">

- **Additional context**:
- I am trying to sign in, but OAuth is temp disabled and I cannot because my account has no assigned password nor email. It's associated with my github...

**Comment by vednoc** [comment]
Same as #148. Otherwise, wait for #137 to get merged.

**Comment by vednoc** [comment]
OAuth has been re-enabled, so you can use your GitHub account to sign in once again.
