### ISSUE TITLE
Account Verification to Prevent Bot Abuse

### ISSUE THREAD

**Issue by AbhayAysola** [userstyles-world/userstyles.world#15]
**Describe the change you'd like**:
Account verification to prevent bot abuse.
**Additional context**:
Use email verification or captcha to prevent spam or bot abuse when registering a new account.

**Comment by vednoc** [comment]
This is in the works. I have to set up a mail service before being able to implement this functionality. Hopefully we won't have a need for any kind of captcha. 😄

**Comment by AbhayAysola** [comment]
> This is in the works. I have to set up a mail service before being able to implement this functionality. Hopefully we won't have a need for any kind of captcha. 😄

Good to know, I was also thinking about signing up/logging in via GIthub or Google Accounts which could be pretty useful

**Comment by vednoc** [comment]
IIRC that requires OAUTH. It will probably be implemented down the road.
