### ISSUE TITLE
Can't remove preview image

### ISSUE THREAD

**Issue by a0eoc** [userstyles-world/userstyles.world#154]
**Steps to reproduce**:
- Open style edit page
- Remove URL from the _Preview image URL_ section
> Hint: To remove preview image, remove the URL from field below.
- _Save changes_
- The preview image isn't removed, the URL stays in the same place

**Additional context**:
- Tried on multiple styles
- Tried in other browser
- Hard refresh, opening in other browser doesn't change anything

So, i think the issue is on the website's end.
Would be good to add a checkbox or button here to remove the preview or better all it's versions.

Sorry, your issue template didn't worked well there.

**Comment by vednoc** [comment]
I remember this was working properly. No idea what happened, but I've impressed myself yet again. 😶

Thank you so much for contributing. Feel free to let me know whenever you can reproduce an issue even once or twice. Usually that's enough and you won't have to spend too much time on it.

**Comment by vednoc** [comment]
Oh, and I'll fix this bug now and leave the button for another time since it will need some UI rework because we already have too many buttons.

**Comment by a0eoc** [comment]
It works now!

> Usually that's enough and you won't have to spend too much time on it.
Your website is very fast and quite intuitive, so it does not take much time. I think it's better to double check before publishing the issue.
