### ISSUE TITLE
"Install" button opens a .css file and not opens Stylus' install menu

### ISSUE THREAD

**Issue by TuTAH1** [userstyles-world/userstyles.world#157]
- **Browser**:
Vivaldi 5.6.2867.62 (Stable channel) (64 bits) 
- **Screenshot**:
![image](https://user-images.githubusercontent.com/15982179/230526618-16e0e703-db7b-447c-891a-5776139da83f.png)
- **Additional context**:
In other sites (uso.kkx.one, greasyfork.org, etc.) stylus' install menu opens as it should:
![image](https://user-images.githubusercontent.com/15982179/230526727-f8bdd07d-6dfe-43fc-a686-138db640b9d6.png)

**Comment by vednoc** [comment]
Strange, it opens the install page without any issues on `Vivaldi 5.7.2921.53 (Stable channel) stable (64-bit)`:

![image](https://user-images.githubusercontent.com/18245694/230587409-39c03885-02ca-4250-a302-380cb94f6e08.png)

Open DevTools on that URL, click on "Console" tab, and refresh the page. Maybe you'll be able to see some kind of an error. Something else to try is to restart your browser. Also, update your browser to the latest version and try again. This feature is what we use to install userstyles from day one, and this is the first time it hasn't worked for someone.

**Comment by TuTAH1** [comment]
> Strange, it opens the install page without any issues on `Vivaldi 5.7.2921.53 (Stable channel) stable (64-bit)`:
> 
> ![image](https://user-images.githubusercontent.com/18245694/230587409-39c03885-02ca-4250-a302-380cb94f6e08.png)
> 
> Open DevTools on that URL, click on "Console" tab, and refresh the page. Maybe you'll be able to see some kind of an error. Something else to try is to restart your browser. Also, update your browser to the latest version and try again. This feature is what we use to install userstyles from day one, and this is the first time it hasn't worked for someone.

I get these errors in the console on the style page (where "install" button is located:
![image](https://user-images.githubusercontent.com/15982179/230599251-65093643-3294-4003-aea7-d7ff1f51181d.png)

 after clicking "install":
![image](https://user-images.githubusercontent.com/15982179/230599374-a3f84294-84fa-4540-b88a-4e84fc6e5816.png)

I had this problem for a long time, but I forgot to write about it. Reinstalling Stylus not works. Other profiles don't works too. I checked other browser (Edge) and it's worked here. I'll also try this and lastest version of Vivaldi on other PC and say results.

**Comment by vednoc** [comment]
Looks like these errors and warnings are coming from other extensions. We don't use any CDNs. We certainly don't use Google Analytics. You could also try disabling all extensions other than Stylus in order to see if that changes anything.

**Comment by TuTAH1** [comment]
I find a funny thing, that style install menu actually appears if I reload the page with .css. I'm not sure what is causing it, but I just made a tiny userscript for reloading page of that specific address automatically and now I can see the install window nearly immidiatly after clicking on "install" button.

```js
// ==UserScript==
// @name         Reload install css page.
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  Reload .css page of userstyles.world for redirecting to stylus' install scrypt window
// @author       Титан
// @match        https://userstyles.world/api/style/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=userstyles.world
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    window.location.reload();
})();
```

It's strange how many months I didn't know about the existence of such a simple solution

**Comment by vednoc** [comment]
I'm so glad you figured out an easy workaround! Since Vivaldi is heavily modified, it comes at a cost of having to troubleshoot weird issues every once in a while. It probably would've been left unsolved if you didn't reach out.
