### ISSUE TITLE
Sort button is missing

### ISSUE THREAD

**Issue by sapondanaisriwan** [userstyles-world/userstyles.world#163]
- **Screenshot**:
![zNNaeCLjZ2](https://user-images.githubusercontent.com/64634605/230786492-9db710ce-1aaf-4ffb-95da-58730639d358.png)
Expected:
![msedge_kPZP5DqEK9](https://user-images.githubusercontent.com/64634605/230786517-19ebdda4-ee3f-4034-a30b-b347d2559ffc.png)

**Comment by vednoc** [comment]
That's intended, but the inline JS fails to work due to CSP. 😓

**Comment by vednoc** [comment]
It's fixed now, though we probably want to remove the inline JS and add it to TS. BTW, the "Sort" button is still there, but it's only visible when JS is disabled.
