### ISSUE TITLE
Rounding counts to thousands with two decimals and 'K' unit prefix is counterproductive

### ISSUE THREAD

**Issue by myfonj** [userstyles-world/userstyles.world#170]
**Describe the change you'd like**:

I'd like to see precise number counts everywhere or "unit prefixes" (suffixes) only when they would serve some space-preserving purpose. Current state with unit suffix and decimal point effectively consumes *more* visual space and is way more difficult to comprehend than simple "raw" number.

**Additional context**:

![image](https://user-images.githubusercontent.com/1761395/235120324-d071596c-1763-4440-a8e9-3976fd9c17f5.png)

Fig: raw `12345` in common proportional font is effectively shorter representation of the number than its "abbreviation". Formatted yet precise representation have comparatively same length:

| Format | "Name" | Comment |
| -: | - | - |
| 12345 | raw | precise |
| 12.35K | abbreviated | imprecise, should "save space" |
| 12&thinsp;345 | thinsp | "long" precise "formatted" with `&thinsp;` separator (`*`) |
| 12 345 | space | "long" precise "formatted" with regular space separator (`*`) |

![image](https://user-images.githubusercontent.com/1761395/235124446-95ffd100-efde-446a-9150-2ab50d6e5714.png)

---

`*` for visual separators I'd advise to use construct like `1<span style="letter-spacing: .3em">2</span>345` rather than using real characters, because it works more predictably and is more accessible.

**Comment by vednoc** [comment]
Thank you so much for the feedback! The idea is to save some space in cards by showing a "relative" number count. I made some improvements to it, though I would happily make further tweaks if necessary. The issue will close automatically, so feel free to either reopen it or open a new one.
