### ISSUE TITLE
Style pages are broken by invalid HTML syntax

### ISSUE THREAD

**Issue by a0eoc** [userstyles-world/userstyles.world#186]
...by unclosed tags like `<i>`, `<b>`, `<s>`, `<u>`, `<a href="http://example.com">` because no proper sanitation is done to them.

Example:
https://userstyles.world/style/59
`<b>` tag here makes some UI text bold, breaks display of the style code and footer.

**Comment by 1280px** [comment]
unclosed \<table> leads to a pretty interesting result, when the rest of the page is "captured" inside the description block:

![2023-06-02-18-10-14](https://github.com/userstyles-world/userstyles.world/assets/71165491/8f658891-9768-47c5-992c-42cd7b288258)

**Comment by vednoc** [comment]
The fix is live.
