### ISSUE TITLE
"Incorrect userstyle data was entered. Please review the fields bellow. Description must be up to 160 characters."

### ISSUE THREAD

**Issue by blyad2137** [userstyles-world/userstyles.world#195]
I cant even update my userCSS's and this is getting frustrating.
![image](https://github.com/userstyles-world/userstyles.world/assets/86572965/4aa771f9-7ce4-4353-b03a-aabe0abf83b6)

**Comment by vednoc** [comment]
I made some improvements and somehow forgot to comment on them. Anyways, you'll need to update description field to fit our new requirements. For example, move everything after the first line to "notes" section and the error should be resolved. Also, check hints for what fields could contain and what they're used for.
