### ISSUE TITLE
Import from github

### ISSUE THREAD

**Issue by LamprechtHase** [userstyles-world/userstyles.world#198]
I like to import a style hosted on github and I'm facing the issue that the "Import URL" field on "https://userstyles.world/import" won't accept anything I enter.
I assume that this should be a link to the CSS code like "https://raw.githubusercontent.com/.../userContent.css" for example.
How is importing a style from github supposed to work?

**Comment by vednoc** [comment]
The file needs to have `.user.css` extension, or `.user.styl` if you're using Stylus-lang preprocessor. You can see examples of import URLs for most of my userstyles: https://userstyles.world/user/vednoc.

**Comment by LamprechtHase** [comment]
Thank you very much! Changing the extension solved the issue.

**Comment by LamprechtHase** [comment]
Meanwhile I found some very helpful documentation:
https://github.com/openstyles/stylus/wiki/Writing-UserCSS
