### ISSUE TITLE
Incorrect Sorting

### ISSUE THREAD

**Issue by cyfung1031** [userstyles-world/userstyles.world#204]
@vednoc malfunction of sorting in UserStyles.world.

It happens for Explore and Search

Take the following as one of the examples.

https://userstyles.world/search?q=youtube&sort=mostinstalls

The [first page](https://userstyles.world/search?page=1&sort=mostinstalls&q=youtube) will show from [YouTube Player Debloater](https://userstyles.world/style/858/youtube-player-debloater) (4165 installs) to [Youtube](https://userstyles.world/style/8839/youtube) (12 installs)

The [second page](https://userstyles.world/search?page=2&sort=mostinstalls&q=youtube) will show from [Old Youtube Layout In 2021-2022](https://userstyles.world/style/6944/old-youtube-layout-in-2021-2022) (35.2K installs) to [Youtube Minimize Navbar](https://userstyles.world/style/10031/youtube-minimize-navbar) (4 installs)

The [third page](https://userstyles.world/search?page=3&sort=mostinstalls&q=youtube) will show from [YouTube Square Avatars](https://userstyles.world/style/1089/youtube-square-avatars) (6004 installs) to [youtube - no video pane (for music)](https://userstyles.world/style/9952/youtube-no-video-pane-for-music) (7 installs)

... and so on

Obviously, the sorting is completely broken. The first page first item has just 4165 installs, it is smaller than second page (35.2k) first item and third page first item (6004)

This also happens in other sorting order. I guess it is just sorting the results from the page with "default sorting", not the full sorting from the entire result list.

**Comment by vednoc** [comment]
We've known about this bug for a while now, and @Gusted started working on a fix for it. There's another way to go about it, but it requires fixing #112 first, then switching from Bleve to SQLite for our search engine. It's next on my list of things to fix (after my current task of rewriting the UI, and side-tasks that @a0eoc gives me). 😅

**Comment by vednoc** [comment]
I prioritized this issue and it's fixed now—we switched, at least temporarily, to SQLite. If you run into more issues, please let us know.
