### ISSUE TITLE
SQLite FTS Query Syntax is not working as expected

### ISSUE THREAD

**Issue by a0eoc** [userstyles-world/userstyles.world#227]
After search rewrite in SQL, it was advised to use this syntax. However, it is not that useful when AND only works with the words standing near each other.

Additional context: trigram tokenizer.

**Comment by vednoc** [comment]
For more context, @a0eoc searched for "debloat AND vk". As noted in https://sqlite.org/fts5.html#the_trigram_tokenizer, substring has to be three or more unicode characters. We could check the length of search keyword and show an error if that requirement isn't met. Additionally, we might want to show a similar error when advanced search syntax is used but no results are returned.
