### ISSUE TITLE
Irrelevant Search Results shown

### ISSUE THREAD

**Issue by cyfung1031** [userstyles-world/userstyles.world#230]
Example: https://userstyles.world/search?q=youtube&sort=mostinstalls

(Same issue for "Most Installs", "Most View", "Rating high to low", etc)

<img width="1290" alt="Screen Shot 2023-06-24 at 21 08 28" src="https://github.com/userstyles-world/userstyles.world/assets/44498510/f7fbe1a2-5e3c-41d7-8bf1-b2bb958d644f">

In the highlighted two results in the screenshots, "youtube" is not found in neither their title, their description, nor their coding.

**Comment by a0eoc** [comment]
This is because the author put links to youtube videos in the notes of these styles. You can find them by searching the page source code, not the page itself.
Maybe @vednoc have something in mind to fix that, but now its more like a feature.

**Comment by vednoc** [comment]
One way to fix this is by querying specific columns: `name:youtube`. It would work great with #128. This is how things work under the hood, especially when all the ranking/relevance goes away after sorting via other methods.

**Comment by vednoc** [comment]
Closing this issue as it was fixed in https://github.com/userstyles-world/userstyles.world/commit/f9792732dbc53fe51e7354e63645bf46a9c3b09b.
