### ISSUE TITLE
USo-archive is missing data

### ISSUE THREAD

**Issue by decembre** [userstyles-world/userstyles.world#256]
With:
<a href="https://userstyles.world/style/66/stream-tolbek-clones-widescreen-v-54">[Stream - Tolbek + Clones Widescreen](https://userstyles.world/style/66/stream-tolbek-clones-widescreen-v-54)</a>
Which stay at the v.54, but on Usertyles.org it is at v.59:
<a href="https://userstyles.org/styles/170956/stream-tolbek-clones-widescreen-v-59">[Stream - Tolbek + Clones Widescreen v.59](https://userstyles.org/styles/170956/stream-tolbek-clones-widescreen-v-59)</a>

Same for:
<a href="https://userstyles.world/style/9449/stream-tolbek-clones-widescreen-tmdb-v-4">[Stream - Tolbek + Clones Widescreen + TMDB v.4](https://userstyles.world/style/9449/stream-tolbek-clones-widescreen-tmdb-v-4)</a>
It stay at v.4, on Userstyles.orh it is now v.6:
<a href="https://userstyles.org/styles/262937/stream-tolbek-clones-widescreen-tmdb-v-6">[Stream - Tolbek + Clones Widescreen + TMDB v.6](https://userstyles.org/styles/262937/stream-tolbek-clones-widescreen-tmdb-v-6)</a>

For the both, i noticed that their descriptions was too long, so i updated them by making it short:
No auto update.
I rewrite a little bit the code and up the version:
no auto update always....

**Comment by a0eoc** [comment]
Current contents of your styles are the same as in the links they're mirrored from (`https://raw.githubusercontent.com/uso-archive/data/flomaster/data/usercss/170956.user.css`, `https://raw.githubusercontent.com/uso-archive/data/flomaster/data/usercss/262937.user.css`), so there are no updates for userstyles.world to fetch.  
Apparently [USo archive ](https://github.com/uso-archive/data) is out of date. It also has a badge saying that auto update is failing. Your styles are fetched from USo archive in UserCSS format, not userstyles.org itself.

Consider moving away from userstyles.org, as many other authors have already done. You can publish updates for your styles directly from Stylus, or host them on GitHub and mirror from it. [Example](https://github.com/vednoc/dark-github/blob/main/github.user.styl).  
If moving, don't forget to add some note that the styles are no longer updated on USo so users can continue getting updates from somewhere else.

**Comment by decembre** [comment]
Thank.
For now, i prefer to keep userstles.org too, because many users use it with the Stylish addon.
I use myself an older version of it, without privacy problems.

It seems Uso Archives work on the problem about Auto update:
I wait to see if it is better after that.

If i need to manually Update my userstyles, which version i need to use to don't break the update for my users?
I use an version number is totally different...

**Comment by a0eoc** [comment]
Keep using `date` versions like you already did on USw, just make sure to use the current date when updating.

**Comment by decembre** [comment]
Ok...
:-)

**Comment by decembre** [comment]
Seems https://uso.kkx.one/ have some problem with its Github repo:
<a href="https://github.com/uso-archive/data/issues/48">[Oh, i've also got a funny email from github lmao, not sure if deleting those branches will make them happy](https://github.com/uso-archive/data/issues/48)</a>

Can i use uso-archive.surge.sh, which seems updated, to replace it:
 <a href="https://uso-archive.surge.sh/?sort=updated&amp;author=decembre">[UserStyles.org Archive](https://uso-archive.surge.sh/?sort=updated&author=decembre)</a>

**Comment by decembre** [comment]
seems solved....

**Comment by vednoc** [comment]
Keep an eye on https://github.com/uso-archive/data/issues/48. This issue will be closed once things are fixed over there.

**Comment by decembre** [comment]
Now it is fixed:
the site work again!
:-)
