### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by SeerLite** [userstyles-world/userstyles.world#27]
Hi!

The page at https://userstyles.world/ gives a 502 Bad Gateway error. Is the site under maintainance?

I read a while ago it was being rewritten or something along the lines. Does that have anything to do with it? Or is it just a configuration error?

Thank you for the work in userstyles.world!

**Comment by vednoc** [comment]
Hi there!

It will be up in just a bit, I'm preparing everything for a new release.

**Comment by vednoc** [comment]
And we're live! 🎉

It was supposed to be live earlier, but embedding files into executable gave me a headache, so I had to clone the repository and build it on the server. 😅 It's not a big deal, but it's definitely worth looking into resolving for future releases.

**Comment by SeerLite** [comment]
Thank you!!

I haven't looked at this project in a while, is this release the first time the new non-static site is live, or has it been around for a while already? It's looking amazing!

**Comment by vednoc** [comment]
It's a third time thus far. First one was alpha about a month ago. Second one was only announced here and on Discord a couple of weeks ago. The third one got `@everyone` ping on Discord after it went live, and now it's being tested and we have more new userstyles. Exciting times ahead!

I'm really glad you like it! Thank you for the support. 🎉
