### ISSUE TITLE
Error: Couldn't parse param "id"

### ISSUE THREAD

**Issue by haydenbroadhead** [userstyles-world/userstyles.world#296]
Hello,

I get the following error when trying to publish onto a usersyle uploaded from a different computer to the one it was created on.

1. Create user style one one computer and publish
2. Login and download style from different machine
3. Make a change and publish onto the same style on userstyles.world

I've tried to disconnect and repeat; with no luck.

I'm not sure what the id refers to. Am i missing some annotation on the style? 

- **Browser**:
- Firefox
- **Screenshot**:
![Screenshot_20240202_222347](https://github.com/userstyles-world/userstyles.world/assets/2504889/be050cb1-8ecc-42c1-9bc1-3a1cebb4c9bf)

- **Additional context**:

**Comment by a0eoc** [comment]
Hello,
This is Stylus bug: openstyles/stylus#1736
Please update or downgrade Stylus in an available way. One of ways is to wait for it to be reviewed by Mozilla Add-ons team, but it might take a while.

**Comment by breatfr** [comment]
same in brave browser
