### ISSUE TITLE
Mirroring: I cannot set my GitLbab URL :(

### ISSUE THREAD

**Issue by vitaly-zdanevich** [userstyles-world/userstyles.world#300]
Hi, I want to mirror this URL https://gitlab.com/vitaly-zdanevich/evernote-css-black/-/raw/main/main.css so on my `git push` it will update the GitLab and userstyles.world

![image](https://github.com/userstyles-world/userstyles.world/assets/3514015/2c8d8b90-f668-4f14-a102-ae318c1f6471)

**Comment by a0eoc** [comment]
@vitaly-zdanevich the file extenstion must be `.user.css`.
ref #298
ref Stylus guides: [[1]](https://github.com/openstyles/stylus/wiki/Writing-UserCSS#initial-installation-and-live-reload), [[2]](https://github.com/openstyles/stylus/wiki/Writing-UserCSS#hosting-a-usercss).
