### ISSUE TITLE
The nav does a horizontal scroll on small devices

### ISSUE THREAD

**Issue by santi-san** [userstyles-world/userstyles.world#33]
**Describe the change you'd like**: Make a hamburger menu for small devices or just show the logo without the "UserStyles.world" text.

**Additional context**: Tested on firefox 87.0 

![image](https://user-images.githubusercontent.com/73315658/113489758-4c3ff100-949c-11eb-94bd-d014b55a65ae.png)

Note: On chrome v89.0.4 doesn't create the horizontal scroll

**Comment by vednoc** [comment]
Since we'll have search page soon, I went ahead and implemented a proper menu. If there are ways that it can be improved, do let us know. 🎉

**Comment by santi-san** [comment]
> 
> 
> Since we'll have search page soon, I went ahead and implemented a proper menu. If there are ways that it can be improved, do let us know. 🎉

Minor change: The transition of the hamburger menu is way too fast.

**Comment by Gusted** [comment]
> > Since we'll have search page soon, I went ahead and implemented a proper menu. If there are ways that it can be improved, do let us know. tada
> 
> Minor change: The transition of the hamburger menu is way too fast.

Agreed, #35
