### ISSUE TITLE
Menu: Add & Import 

### ISSUE THREAD

**Issue by santi-san** [userstyles-world/userstyles.world#34]
Makes more sense that both links (add and Import) appear only after login.

![image](https://user-images.githubusercontent.com/73315658/113526758-a1a9fa00-9591-11eb-81b0-62cbef671b77.png)

**Comment by vednoc** [comment]
I think so too, since it's kind of a "dark pattern" right now, but at the same time it shows visitors they can add/import styles. 🤔 

@Gusted Thoughts?

**Comment by Gusted** [comment]
> I think so too, since it's kind of a "dark pattern" right now, but at the same time it shows visitors they can add/import styles. 🤔
> 
> @Gusted Thoughts?

On another note it could show off that you can do those stuff without logging in. Clicking on such link and then getting an error rendered on the login page is unexpected behavior and not user friendly.

_Insert according to statics it will decrease user count_

Just sign-up/login link in the header for non logged in users.
