### ISSUE TITLE
Style parser doesn't ignore whitespace correctly

### ISSUE THREAD

**Issue by RiedleroD** [userstyles-world/userstyles.world#38]
When adding a style, this doesn't get accepted:
```css
@name		newstyle
@namespace	somespace
@version	1.0.1
```
while this does:
```css
@name newstyle
@namespace somespace
@version 1.0.1
```
I assume it doesn't ignore tabs correctly and just stops reading after the first one.

**Comment by Gusted** [comment]
Seems like the code was counting on spaces and didn't account for other valid methods like tabs.
https://github.com/vednoc/go-usercss-parser/pull/1

**Comment by vednoc** [comment]
Should be fixed now. I just updated the server.
