### ISSUE TITLE
Duplicate: Add a verification before import

### ISSUE THREAD

**Issue by decembre** [userstyles-world/userstyles.world#41]
When import userstyles one by one, i think it's easy to have a duplicate....
:-)
So it's possible to have a warning if the import is yet in USw?

**Comment by Gusted** [comment]
We currently just check the style's name. I'm not sure if that is enough to prevent such issue as I don't know a clear example of this. https://github.com/userstyles-world/userstyles.world/blob/main/handlers/style/import.go#L84

**Comment by vednoc** [comment]
The warning will be "Duplicate style name". If it ends up being necessary, we could also check for equality in source code and/or other fields, but I think that having unique style names should be good enough. 

Source: https://github.com/userstyles-world/userstyles.world/blob/653001fb38/models/style.go#L179

**Comment by decembre** [comment]
Checking only the name should not be enough:

If more users come to use the import function (and if batch import became available), i think some error can arrive:
Userstyles as a limitation for the userstyle's name and many userstyle for generic sites ( Google, YouTube...) and a same same type of change (Dark and Gray,..) can easily have a similar name, i suppose.

On greasyfork, i see many userscripts with the same name (and when i want remember them, i need add more infos if i bookmark them).
Not certain it should be a great deal, but if it possible to use another thing than title...

**Comment by vednoc** [comment]
> can easily have a similar name, i suppose

That's why we check both the style name and the user ID. While I agree that it's not enough, it served us well thus far.

> but if it possible to use another thing than title

By adding source code to the comparison, we will probably be good to go in 99.99% of the use-cases.

**Comment by Gusted** [comment]
> By adding source code to the comparison, we will probably be good to go in 99.99% of the use-cases.

Wouldn't take take quite a performance hog?

**Comment by vednoc** [comment]
> Wouldn't take take quite a performance hog?

Maybe. It's worth testing regardless of it being added or not.

**Comment by vednoc** [comment]
Added source code to comparison. If it ends up causing performance issues, we will revisit it.
