### ISSUE TITLE
Make all usertsyles list sortable by date /name / author etc...

### ISSUE THREAD

**Issue by decembre** [userstyles-world/userstyles.world#42]
As they are more usertyles coming, it should be more useful to explore ...

**Comment by vednoc** [comment]
![image](https://user-images.githubusercontent.com/18245694/114238217-8d487180-9984-11eb-8ba9-c806eda8ef82.png)

That's two, three including me. 😄 It kinda shares some functionality with search page.

**Comment by decembre** [comment]
;-)
