### ISSUE TITLE
OAUTH login for GitHub/GitLab/Codeberg

### ISSUE THREAD

**Issue by Gusted** [userstyles-world/userstyles.world#44]
As I'm working on this. Just having a issue :)

Simple flow: Ensure security and possible support PKCE extension for supported services. 

Do some front end to input nickname + password and than let continue the basic register flow by email verification(or not?)

**Comment by vednoc** [comment]
E-mail verification is probably unnecessary. Can you even get the e-mail address with OAuth? I thought the login process works by clicking on the "Sign in with GitHub" button (or equivalent for other platforms), it will then authorize the app (or check if it has already been authorized), and send you to `/account` page. Does it not work that way?

**Comment by Gusted** [comment]
> E-mail verification is probably unnecessary

Depends, as example github sends back emails and a key if they are verified. Then we don't need it. Otherwise we would ask for verification.




>  I thought the login process works by clicking on the "Sign in with GitHub" button (or equivalent for other platforms), it will then authorize the app (or check if it has already been authorized), and send you to `/account` page. Does it not work that way?

Depends.

No you cannot get it trough OAuth. But you can request the users email endpoint which requirere the OAuth token. If we already gave such email than we just give them the correct jwt token otherwise ask for new username and password.
