### ISSUE TITLE
The Auto Update don't update the userstyle name

### ISSUE THREAD

**Issue by decembre** [userstyles-world/userstyles.world#48]
As there is no versioning in userstyles.org, i have the (bad?...) habit to add it in my userstyle name....
Yes, no many user doing that, but for me it's easy like that to see if i have posted my last version without need to open its usertyle page.
Anyway, can you update the name too when there is an change in the CSS in USO ?

Example:
<a href="https://userstyles.world/style/27">Youtube WideScreen (New Design Polymer) v.13 in USw</a>
but the code show it's the v.14.

<a href="https://uso-archive.surge.sh/?author=decembre&amp;sort=updated&amp;style=188453">Youtube WideScreen (New Design Polymer) v.14 in USO</a>
Here the title is good equal to the version in the CSS.

**Comment by vednoc** [comment]
I was going to include it with #37. Most non-code fields will go under a shared option — mirror metadata — once I figure out and test the necessary logic.

**Comment by decembre** [comment]
:-)
