### ISSUE TITLE
I can't add my github profile

### ISSUE THREAD

**Issue by santi-san** [userstyles-world/userstyles.world#50]
- **Browser**: Firefox 87

- **Screenshot**: 
![image](https://user-images.githubusercontent.com/73315658/115159285-cfe70980-a068-11eb-9533-7ee36cbf85d2.png)

- **Additional context**:
My github username has a dash and the pattern used only accept ([a-zA-Z0-9])

**Comment by vednoc** [comment]
I just updated the server, so it should be fixed now. Also, do a force-refresh to get the newest CSS file (form should be aligned to the left side and icon should be inverted and have a margin on the right).

**Comment by santi-san** [comment]
> 
> 
> I just updated the server, so it should be fixed now. Also, do a force-refresh to get the newest CSS file (form should be aligned to the left side and icon should be inverted and have a margin on the right).

Done!,  thanks
![image](https://user-images.githubusercontent.com/73315658/115160041-800a4180-a06c-11eb-9453-c231f24f7abd.png)
