### ISSUE TITLE
Add a notice to install a browser extension like Stylus to be able to install styles

### ISSUE THREAD

**Issue by Freeplayg** [userstyles-world/userstyles.world#52]
**Describe the change you'd like**:
If possible maybe check if the user doesn't have the Stylus extension installed, and replace the "Install Userstyle" button with a "Get Stylus to install this style!" button

If not, maybe a banner would be fine.

**Comment by Gusted** [comment]
@vednoc As we discussed ;). Should be good-to-go.

**Comment by vednoc** [comment]
I thought this was about something else. How can we tell if an extension is already installed?

**Comment by Gusted** [comment]
> How can we tell if an extension is already installed?

🤷🏽 possible have within stylus a little code to remove that banner.

**Comment by vednoc** [comment]
That's what I was thinking. We could also add an option to hide the button in USw Tweaks userstyle.

**Comment by Gusted** [comment]
Sounds good

**Comment by Gusted** [comment]
It is implemented and if you have stylus installed, from the next stylus update on it will remove the notice.

**Comment by vednoc** [comment]
For posterity, it was added in https://github.com/userstyles-world/userstyles.world/commit/2875bc381e0542cf4c27505b3ea96fcb3eda7902 and I forgot to reference the issue in the commit.
