### ISSUE TITLE
Internal Error after Github registration/login

### ISSUE THREAD

**Issue by 1337cookie** [userstyles-world/userstyles.world#62]
After registration using 3rd party login with Github I get `{"data":"Internal Error."}` with http response 500 error.  The same happens after subsequent logins.

![image](https://user-images.githubusercontent.com/15826769/120706009-a72dad00-c50c-11eb-8335-b1133c55942d.png)

**Comment by Gusted** [comment]
https://github.com/userstyles-world/userstyles.world/commit/6f026ba15ab99328a254454d1304cd9512f5526b fixes this issue. It was causing some errors with the database and having non-unique values. @vednoc

**Comment by vednoc** [comment]
I updated the server. Feel free to close the issue if the problem has been resolved.

**Comment by 1337cookie** [comment]
Resolved, Thanks. :)

**Comment by reloxx13** [comment]
i also used github and get an error now when i want to add a style.   
    
![grafik](https://user-images.githubusercontent.com/14855001/125132205-49d8dd00-e104-11eb-9b34-84ebcf42906b.png)


after save click:   
![grafik](https://user-images.githubusercontent.com/14855001/125132245-578e6280-e104-11eb-8a9f-ab0f6ea35d5f.png)


as it says sth about username, u guess its a github error, too.  have set a display name.

**Comment by Gusted** [comment]
> edit: you should add a note that the headers has to be there...

You've made 5 edits, it's not very confusing what this is about. First there's some issue that shouldn't exist. And now their are "headers"?

**Comment by reloxx13** [comment]
> 
> 
> > edit: you should add a note that the headers has to be there...
> 
> You've made 5 edits, it's not very confusing what this is about. First there's some issue that shouldn't exist. And now their are "headers"?

click on edited, click on most recent, done. or read ur email notification with initial text.

**Comment by vednoc** [comment]
> edit: you should add a note that the headers has to be there...

Hi @reloxx13, we do have alerts when mandatory fields in UserStyle metadata header are missing, but that wasn't the issue here.

You've found an unrelated bug. I forgot to take into account add/edit pages when I was working on SEO and meta tags. It should be all fixed now. 😅

Thank you for reporting the issue. 😊
