### ISSUE TITLE
I Have 2 Questions

### ISSUE THREAD

**Issue by Jacob-1999** [userstyles-world/userstyles.world#72]
I would first like to say you all did an amazing job on this project. I never knew it existed, let alone UserStyles archived. I've been using Stylus for a few years and never looked back since.

I have two questions for you,
1. Does this project with the Stylus Firefox extension? (I use Firefox Quantum if that makes a difference.)
2. Do you have a Discord server or may consider creating one? I know you don't know me and there are risks working with someone you have no clue about however I would love to help expand your community onto another platform!

I sincerely apologize for not following the format you've created however I couldn't think how to fit my content into the format.

**Comment by Gusted** [comment]
Hi @Jacob-1999!

Thank you for looking into USw.

I think next time the [discussion](https://github.com/userstyles-world/userstyles.world/discussions) page can be used for such questions. 

1) What do you mean exactly? I think you got the wording incorrect for this question.
2) We currently have a discord, it's still private for now. However we are considering making it public.

Regards,
Gusted

**Comment by Jacob-1999** [comment]
Apologizes for not noticing the discussion page. Does USw work with the Stylus extension? ![image](https://i.imgur.com/NCM63uy.png)

**Comment by Gusted** [comment]
Yes, USw works with Stylus and stylus works with USw. The latest stylus update should be able to fetches USw's index and publish styles to USw from the editor.

**Comment by Jacob-1999** [comment]
Awesome, thanks Gusted! Again, amazing job with the project!
