### ISSUE TITLE
Auto Updtae from US Archives don't  care to the change in the userstyle name

### ISSUE THREAD

**Issue by decembre** [userstyles-world/userstyles.world#86]
<a href="https://userstyles.world/style/27/youtube-widescreen-new-design-polymer-v-17-5">Youtube WideScreen (New Design Polymer)</a>
The auto update is done but the Title of it stay to the previous version:
Old was  
Youtube WideScreen (New Design Polymer)  v.17.5
Now, 
Youtube WideScreen (New Design Polymer)  v.18

**Comment by vednoc** [comment]
Seems like my internet connection (or perhaps GitHub) failed to process the response. That's what I get for having _too many open tabs_. 😅
