### ISSUE TITLE
Share style button doesn't work on Firefox

### ISSUE THREAD

**Issue by santi-san** [userstyles-world/userstyles.world#89]
- **Browser**: Firefox 92.0 (64-bits)
Steps to reproduce:
Go to any style.
Press the button clipboard on "Share style".

All extensions where disabled before.

Works on chrome Versión 93.0.4577.63 (Build oficial) (64 bits)

**Comment by Gusted** [comment]
Wow, seems like I missed that while refactoring the code. It should be fixed by https://github.com/userstyles-world/userstyles.world/commit/e1957f3cdbae1dcc467b8e204f99eada9ecf030c which was just deployed to the server.

**Comment by santi-san** [comment]
> 
> 
> Wow, seems like I missed that while refactoring the code. It should be fixed by [e1957f3](https://github.com/userstyles-world/userstyles.world/commit/e1957f3cdbae1dcc467b8e204f99eada9ecf030c) which was just deployed to the server.
Solved, it's working now,
