### ISSUE TITLE
Styles with @advanced do not show up in Stylus feed.

### ISSUE THREAD

**Issue by blyad2137** [userstyles-world/userstyles.world#94]
Well, as in title. This only applies to USw, styles with @advanced from Archives do show up.

No USw version, only Archives.
![image](https://user-images.githubusercontent.com/86572965/135129973-b6621b20-43a0-477c-bc73-2816cec94f65.png)

USw Tweaks do not show up too.
![image](https://user-images.githubusercontent.com/86572965/135130100-4936030b-75d8-4369-829b-afa0c37d9589.png)

**Comment by Gusted** [comment]
Hi @blyad2137!

I don't see any issue here, as I can clearly see the USW's version of this within the stylus feed. 
Thereby there is no special code for `@advanced` styles. Also this does seems like a issue that needs to be done
on the stylus repo and not on the USw repo.

**Comment by vednoc** [comment]
Seems like Stylus filters out installed userstyles. I can see USw Tweaks and USw Enhancements in the list, but once either one is installed, it's also removed from the inline search.

**Comment by blyad2137** [comment]
Okay this makes more sense now, didn't notice this before. Thanks.

//close
