### ISSUE TITLE
How to change font size for CSS code in the editor ?

### ISSUE THREAD

**Issue by mlipok** [userstyles-world/userstyles.world#99]
How to change font size for CSS code in the editor ?

**Comment by Gusted** [comment]
Hi @mlipok

Which editor?

**Comment by mlipok** [comment]
Editor in Stylus:
![image](https://user-images.githubusercontent.com/11089482/147981619-950691e1-9253-4103-a16c-3b541a4f7dee.png)


I was trying:
```

@-moz-document url-prefix("chrome-extension://apmmpaebfobifelkijhaljbmpcgbjbdo/edit.html.*") {
div.CodeMirror {
    outline: none !important;
    font-size: x-large !important;
}
}

```

**Comment by Gusted** [comment]
This is the wrong place to ask such questions then. We don't handle CSS questions here.

**Comment by vednoc** [comment]
The `url-prefix` doesn't support regex, so you would need to remove `.*` from it. To make it even better, use the following:

```diff
-@-moz-document url-prefix("chrome-extension://apmmpaebfobifelkijhaljbmpcgbjbdo/edit.html.*") {
+@-moz-document regexp("(moz|chrome)-extension://.*") {
div.CodeMirror {
    outline: none !important;
    font-size: x-large !important;
}
}
```
